
import Head from 'next/head';
import "./globals.css";


export const metadata = {
  title: "Valentine",
  description: "Generated by create next app",
};


const Layout = ({ children }) => {
  
  return (
    <>
      <Head>
        {/* Other head elements */}
        {typeof document !== 'undefined' && (
          <script
            dangerouslySetInnerHTML={{
              __html: `
                (function(h,o,t,j,a,r){
                  h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                  h._hjSettings={hjid:3884300,hjsv:6};
                  a=o.getElementsByTagName('head')[0];
                  r=o.createElement('script');r.async=1;
                  r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                  a.appendChild(r);
                })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
              `,
            }}
          />
        )}
      </Head>
      {/* Your page content */}
      {children}
    </>
  );
};

export default Layout;
