import { Inter } from "next/font/google";
import "./globals.css";
import Hotjar from '@hotjar/browser';



const inter = Inter({ subsets: ["latin"] });
const siteId = 3884300;
const hotjarVersion = 6;

Hotjar.init(siteId, hotjarVersion);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
